name: Gmail SQLite Automation

on:
  schedule:
    - cron: '*/5 * * * *'

  workflow_dispatch:

jobs:

  run-job:

    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4


      # RESTORE SAME DATABASE

      - name: Restore Database

        uses: actions/cache/restore@v4

        with:

          path: |

            github-actions-db

            db-backups

            processed

          key: sqlite-main


      - name: Debug Existing Database

        run: |

          echo "DATABASE"

          ls -la github-actions-db || true

          echo ""

          echo "BACKUPS"

          ls -la db-backups || true


      - name: Setup Java

        uses: actions/setup-java@v4

        with:

          distribution: temurin

          java-version: 17


      - name: Create Runtime Folders

        run: |

          mkdir -p input
          mkdir -p output
          mkdir -p github-actions-db
          mkdir -p db-backups
          mkdir -p processed
          mkdir -p failed
          mkdir -p logs


      - name: Build

        run: |

          mvn clean package -DskipTests


      - name: Run Automation

        env:

          MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}

          MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}

        run: |

          java -jar target/gmail-sqlite-automation-1.0.0.jar


      # OVERWRITE CACHE WITH NEW DB

      - name: Delete Previous Cache Lock

        continue-on-error: true

        run: |

          echo "Preparing DB"


      - name: Save Database

        if: always()

        uses: actions/cache/save@v4

        with:

          path: |

            github-actions-db

            db-backups

            processed

          key: sqlite-main-${{ github.run_number }}


      - name: Upload Artifacts

        if: always()

        uses: actions/upload-artifact@v4

        with:

          name: automation-files

          path: |

            github-actions-db

            db-backups

            output

            processed

            logs
